package com.ucaldas.posgrados.Entity;

public enum TiposEjecucionPresupuestal {
    GENERAL, TRANSFERENCIA, OTRO, DESCUENTO, INGRESO, INVERSION, SERVICIO_DOCENTE, OTRO_SERVICIO_DOCENTE,
    SERVICIO_NO_DOCENTE, RECURRENTE_ADMINISTRACION, VIAJE
}
